/*
 * FixedMidashi JavaScript Library, version 1.6 (2014/11/23)
 * http://hp.vector.co.jp/authors/VA056612/fixed_midashi/
 * Copyright (C) 2012-2014 K.Koiso
 */

/* Exsample */
/*******************************************************************
 <script type="text/javascript" src="hoge/fixed_midashi.js"></script>

 <!-- body mode -->
 <body onLoad="FixedMidashi.create();">
 <table _fixedhead="rows:1; cols:1">
 ...

 <!-- div mode -->
 <style type="text/css" media="screen">
 div.scroll_div { overflow: auto; }
 </style>
 <body onLoad="FixedMidashi.create();">
 <div class="scroll_div">
 <table _fixedhead="rows:1; cols:1">
 ...
 *******************************************************************/

var FixedMidashi = new function()
{

    var DISABLED = false;

    var ROWS = 1;
    var COLS = 0;
    var DIV_FULL_MODE = false;
    var COPY_ID = true;
    var BORDER_COLOR = null;
    var BORDER_STYLE = null;
    var BORDER_WIDTH = null;

    var DIV_MIN_WIDTH = 150;
    var DIV_MIN_HEIGHT = 150;

    var RADIO_PREFIX = "_FIXED_HEADER_";

    var POS_FIXED    = 1;
    var POS_ABSOLUTE = 2;
    var POS_MIX      = 3;
    var _positionMode = -1;

    var l="textarea",i="password",h="checkbox",f="select-multiple",e="select-one",g="change",k="radio",j="INPUT",Qb="sync",Pb="transparent",Ob="TD",Nb="0px",Mb="absolute",Lb="none",Kb="hidden",Jb="auto",Ib="",Hb="THEAD",Gb="scroll",n="resize",Fb=-1,Eb=null,Db=true,Cb=false,Bb=this;
    var TIMER_WATCH_TABLESIZE=3e3,TID_HEADER="H",TID_NUMBER="N",TID_CORNER="C",PX="px",HEIGHT_MARGIN=10,MIN_SIZE=1,_isIE=Cb,_IEver=0,_isIE11=Cb,_isFirefox=Cb,_isOpera=Cb,_isSafari=Cb,_isChrome=Cb,_isMobile=Cb,_isBackCompat=Cb,_fixedHeaders=Eb,_fixedList=Eb,_body=Eb,_resizeTimerId=Eb,_execFlag=Cb,_IE_retryCount=0;
    Bb.create=function(){var f="_fixedhead";if(DISABLED)return Fb;if(!document.body.getBoundingClientRect)return -2;if(!window.addEventListener&&!window.attachEvent)return -3;var l=(new Date).getTime(),h=_fixedHeaders==Eb;if(!h)for(var b=0;b<_fixedHeaders.length;b++)_fixedHeaders[b].removeAllTables(Cb);for(var i=document.body.getElementsByTagName("TABLE"),e=[],b=0;b<i.length;b++){var c=i[b],d=c.getAttribute(f);if(d==Eb)d=c._fixedhead;if(d==undefined)continue;if(c.rows.length==0)continue;e.push(c)}if(e.length==0)return -4;var g=Eb;if(h){var a=navigator.userAgent.toLowerCase();_isIE=a.indexOf("msie")>=0;if(_isIE){var j=a.indexOf("msie"),m=a.indexOf(";",j);_IEver=Number(a.substring(j+5,m))}if(!_isIE)_isIE11=a.indexOf("trident")>=0;_isFirefox=a.indexOf("firefox")>=0;_isOpera=a.indexOf("opera")>=0;_isSafari=a.indexOf("safari")>=0&&a.indexOf("chrome")<0;_isChrome=a.indexOf("chrome")>=0;_isMobile=a.indexOf("mobile")>=0;if(_isIE&&_rect(i[0]).right>=1e4&&_IE_retryCount<10){setTimeout(FixedMidashi.create,10);_IE_retryCount++;return -5}_isBackCompat=document.compatMode=="BackCompat";_body=_isBackCompat?document.body:document.documentElement;if(_isIE&&(_IEver<=7||_IEver<=9&&_isBackCompat))_positionMode=POS_ABSOLUTE;else if(_positionMode==Fb){_positionMode=POS_MIX;if(_isMobile)_positionMode=POS_FIXED}if(_isIE&&_IEver==8&&!_isBackCompat)_fixedList=new _FixedElementList;if(_isFirefox)g=_createObjectForFirefox();_addEventListener(window,n,_onBodyResize);_isMobile&&_addEventListener(window,"orientationchange",_onBodyResize);(_isFirefox||_isSafari)&&!_isMobile&&TIMER_WATCH_TABLESIZE>=0&&setInterval(_checkZoom,TIMER_WATCH_TABLESIZE);_addEventListener(window,Gb,_onBodyScroll)}_fixedHeaders=[];for(var b=0;b<e.length;b++){var c=e[b],d=c.getAttribute(f);if(d==Eb)d=c._fixedhead;var k=_createFixedHeader(c,d,e.length);_fixedHeaders.push(k)}_execute("init");h&&_createCSS("print",".fixed_header_display_none_at_print { display: none; visibility: hidden; }");g!=Eb&&g.parentNode.removeChild(g);return (new Date).getTime()-l};
    function _checkZoom(){if(_fixedHeaders==Eb)return;for(var a=0;a<_fixedHeaders.length;a++)if(_fixedHeaders[a].checkZoom()){_execute(n);break}}
    Bb.remove=function(){if(_fixedHeaders==Eb)return;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].removeAllTables(Db);_fixedHeaders=[]};
    Bb.syncValue=function(a){if(_fixedHeaders==Eb)return;if(!a)return;_copyValues(a)};
    Bb.syncStyle=function(a,d){if(_fixedHeaders==Eb)return;if(!a)return;if(_fixedList!=Eb){var e=_fixedList.getAll(a);if(e==Eb)return;for(var b=0;b<e.length;b++)_copyStyle(a,e[b],d);return}var c=a.$FXH_FIXED_ELEMENT;if(c==undefined)return;if(!c.$IS_ARRAY)_copyStyle(a,c,d);else for(var b=0;b<c.length;b++)_copyStyle(a,c[b],d)};
    Bb.getFixedElement=function(b){if(_fixedHeaders==Eb)return Eb;if(!b)return Eb;if(_fixedList!=Eb)return _fixedList.get(b);var a=b.$FXH_FIXED_ELEMENT;if(!a)return Eb;if(!a.$IS_ARRAY)return a;if(a.length==0)return Eb;return a[a.length-1]};
    Bb.getFixedElements=function(b){if(_fixedHeaders==Eb)return Eb;if(!b)return Eb;if(_fixedList!=Eb)return _fixedList.getAll(b);var a=b.$FXH_FIXED_ELEMENT;if(!a)return Eb;if(a.$IS_ARRAY&&a.length==0)return Eb;var c=[];if(!a.$IS_ARRAY)c.push(a);else for(var d=0;d<a.length;d++)c.push(a[d]);return c};
    Bb.getSourceElement=function(a){if(_fixedHeaders==Eb)return Eb;if(!a)return Eb;var b=a.$SOURCE_ELEMENT;return !b?Eb:b};
    Bb.isFixedElement=function(a){if(_fixedHeaders==Eb)return Cb;if(!a)return Cb;return a.$SOURCE_ELEMENT!=undefined};
    function _createFixedHeader(j,A,y){for(var v=j.rows,u=_cells(v[0]),o=0,e=0;e<u.length;e++)o+=u[e].colSpan;var d=ROWS,i=COLS,c=Fb,b=Fb,t=COPY_ID,f=BORDER_COLOR,g=BORDER_STYLE,h=BORDER_WIDTH,k=Eb,l=1,p=DIV_FULL_MODE,w=_getElementByTagName(j,Hb);if(w!=Eb)d=w.rows.length;for(var x=A.split(";"),e=0;e<x.length;e++){var q=x[e].split(":");if(q.length!=2)continue;var z=_trim(q[0]).toLowerCase(),a=_trim(q[1]);switch(z){case "rows":d=Number(a);break;case "cols":i=Number(a);break;case "div-max-width":c=_percent(a);break;case "div-max-height":b=_percent(a);break;case "div-full-mode":p=a.toLowerCase()=="yes";break;case "copyid":t=a.toLowerCase()=="yes";break;case "border-color":f=a;break;case "border-style":g=a;break;case "border-width":h=a;break;case "bgcolor":k=a;break;case "opacity":l=Number(a)}}if(d<0||d>=Math.min(v.length,11))d=0;if(i<0||i>=Math.min(o,11))i=0;if(!c||c<1||c>100)c=Fb;if(!b||b<1||b>100)b=Fb;if(y>1)p=Cb;if(l<0||l>1)l=1;var m=document.createElement("DIV");if(f!=Eb&&!_setStyle(m,"borderColor",f))f=Eb;if(g!=Eb&&!_setStyle(m,"borderStyle",g))g=Eb;if(h!=Eb&&!_setStyle(m,"borderWidth",h))h=Eb;if(k!=Eb&&!_setStyle(m,"backgroundColor",k))k=Eb;var s=Eb;if(j.parentNode.tagName=="DIV"){var r=j.parentNode,n=r.currentStyle||document.defaultView.getComputedStyle(r,Ib);if(n.overflowX==Jb||n.overflowX==Gb||(n.overflowY==Jb||n.overflowY==Gb))s=r}return new _FixedHeader(s,j,o,d,i,c,b,p,t,f,g,h,k,l)}
    function _onBodyScroll(){for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].onBodyScroll()}
    function _onBodyResize(){if(_execFlag)return;_resizeTimerId!=Eb&&clearTimeout(_resizeTimerId);var a=function(){_execute(n)};
        _resizeTimerId=setTimeout(a,200)}
    function _execute(b){_execFlag=Db;_resizeTimerId=Eb;for(var a=0;a<_fixedHeaders.length;a++)if(b==n)_fixedHeaders[a].initOnResize();else _fixedHeaders[a].init();_resizeSourceDiv();for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].main();_execFlag=Cb}
    function _resizeSourceDiv(){for(var b=Cb,a=0;a<_fixedHeaders.length;a++)if(_fixedHeaders[a].hideAllDivs(Db))b=Db;if(!b)return;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeSourceDiv1();var d=_body.style.overflowX,c=_body.currentStyle||document.defaultView.getComputedStyle(_body,Ib);if(_body.scrollWidth<=_body.clientWidth&&c.overflowX!=Gb)_body.style.overflowX=Kb;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeDivHeight();for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeDivWidth();_body.style.overflowX=d;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeSourceDiv2();for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].hideAllDivs(Cb)}
    function _FixedHeader(a,d,yb,q,y,v,z,kb,C,G,H,I,J,T){var m="CLIENT",u="visible",h="fixed",i="TBODY",g="1px",o=this,f=a!=Eb,c=Eb,b=Eb,e=Eb,fb=0,eb=0,Z=Ib,Y=Ib,L=Eb,N=Eb,B=[],lb=[],R=0,X=0,qb=d.style.zIndex?d.style.zIndex:0,p=Cb,x=Cb,j=0,l=0,ob=0,pb=0,W=0,V=0,Q=0,xb=d.style.display,ab=Fb,cb=Fb,k=Eb,r=Fb,t=Fb,M=Eb,K=Eb;
        o.init=function(){if(J==Eb){var e=f?a:d,b=_getBackgroundColor(e);if(b==Eb){var c=e.parentNode;while(c){b=_getBackgroundColor(c);if(b!=Eb)break;if(c.tagName=="HTML")break;c=c.parentNode}if(b==Eb)b="white"}J=b}if(f){_addEventListener(a,Gb,S);rb();Q=_offsetWidth(d)}jb()};
        o.initOnResize=function(){t=Fb;r=Fb;cb=Fb;ab=Fb;if(f){if(p||v>0)a.style.width=Ib;if(x||z>0)a.style.height=Ib;Q=_offsetWidth(d)}jb()};
        o.removeAllTables=function(d){c&&w(c);b&&w(b);e&&w(e);c=Eb;b=Eb;e=Eb;if(f){_removeEventListener(a,Gb,S);if(d){if(p||v>0)a.style.width=Ib;if(x||z>0)a.style.height=Ib}}};
        o.hideAllDivs=function(h){if(!f)return Cb;var d=c==Eb?Eb:c.parentNode,g=b==Eb?Eb:b.parentNode,j=e==Eb?Eb:e.parentNode;if(h){d&&F(d,DIV_MIN_WIDTH);g&&E(g,DIV_MIN_HEIGHT)}var i=h?Lb:Ib;if(d)d.style.display=i;if(g)g.style.display=i;if(j)j.style.display=i;(p||x||v>0||z>0)&&ub(h);if(h){p&&s(a,DIV_MIN_WIDTH);x&&A(a,DIV_MIN_HEIGHT)}return Db};
        o.resizeSourceDiv1=function(){if(!f)return;var e=k!=Eb?k:d;if(v>0){j=_body.clientWidth/100*v;j=Math.max(j,DIV_MIN_WIDTH);var c=_offsetWidth(e)+W;c=Math.min(c,j);s(a,c)}if(z>0){l=_body.clientHeight/100*z;l=Math.max(l,DIV_MIN_HEIGHT);var b=_offsetHeight(e)+V;b=Math.min(b,l);A(a,b)}};
        o.resizeDivHeight=function(){if(!f)return;if(!x)return;if(_body.scrollHeight>_body.clientHeight){var e=Math.max(_body.scrollHeight-_body.clientHeight,0);a.style.height=Math.max(_body.clientHeight-30,MIN_SIZE)+PX;var g=Math.max(_body.scrollHeight-_body.clientHeight,0);l=_offsetHeight(a)-(g-e)}else{a.style.height=_body.clientHeight+PX;var h=Math.max(_body.scrollHeight-_body.clientHeight,0);l=_offsetHeight(a)-h}l--;l=Math.max(l,DIV_MIN_HEIGHT);var c=k!=Eb?k:d,b=_offsetHeight(c)+V;b=Math.min(b,l);if(kb)b=l;A(a,b)};
        o.resizeDivWidth=function(){if(!f)return;if(!p)return;if(_body.scrollWidth>_body.clientWidth){var e=Math.max(_body.scrollWidth-_body.clientWidth,0);a.style.width=Math.max(_body.clientWidth-16,MIN_SIZE)+PX;var g=Math.max(_body.scrollWidth-_body.clientWidth,0);j=_offsetWidth(a)-(g-e)}else{a.style.width=_body.clientWidth+PX;var h=Math.max(_body.scrollWidth-_body.clientWidth,0);j=_offsetWidth(a)-h}j--;j=Math.max(j,DIV_MIN_WIDTH);var c=k!=Eb?k:d,b=_offsetWidth(c)+W;b=Math.min(b,j);if(kb)b=j;if(_isIE)b--;s(a,b)};
        o.resizeSourceDiv2=function(){if(!f)return;var b=k!=Eb?k:d;if((p||v>0)&&a.scrollWidth>a.clientWidth&&_offsetWidth(a)<j){var e=a.scrollWidth-a.clientWidth,c=Math.min(_offsetWidth(a)+e,j),i=a.style.overflowY;if(_isIE)a.style.overflowY=Kb;s(a,c);if(_isIE)a.style.overflowY=i}if((x||z>0)&&a.scrollHeight>a.clientHeight&&_offsetHeight(a)<l){var e=a.scrollHeight-a.clientHeight,g=Math.min(_offsetHeight(a)+e,l);A(a,g)}if((p||v>0)&&Q>_offsetWidth(b)&&_offsetWidth(a)<j){var h=Q-_offsetWidth(b),c=Math.min(_offsetWidth(a)+h,j);s(a,c)}};
        o.checkZoom=function(){if(Math.abs(_offsetWidth(d)-fb)>=1||Math.abs(_offsetHeight(d)-eb)>=1||_colsWidthList(_cells(d.rows[0]))!=Z||_rowsHeightList(d.rows)!=Y)return Db};
        o.main=function(){var h=_offsetWidth(d),g=_offsetHeight(d),b=fb!=h,a=eb!=g;fb=h;eb=g;var c=_colsWidthList(_cells(d.rows[0]));if(Z!=c){Z=c;b=Db}var e=_rowsHeightList(d.rows);if(Y!=e){Y=e;a=Db}var i=vb(b||a);(i||b||a)&&wb();f&&zb();if(f)S();else bb(Db)};
        function vb(l){if(l){c!=Eb&&w(c);b!=Eb&&w(b);e!=Eb&&w(e);c=Eb;b=Eb;e=Eb}var i=Cb,j=d.rows,k=f?d.parentNode:_body,h=Cb,g=Cb;if(f){h=a.clientHeight<a.scrollHeight&&a.clientHeight!=0;g=a.clientWidth<a.scrollWidth&&a.clientWidth!=0}else{h=_body.clientHeight<_body.scrollHeight;g=_body.clientWidth<_body.scrollWidth}if(q>0&&h)if(_rowsHeight(j,q)+30>=k.clientHeight)h=Cb;if(y>0&&g){var m=_cells(j[0]);if(_colsWidth(m,y)+30>=k.clientWidth)g=Cb}if(y>0&&g){if(b==Eb){b=db(TID_NUMBER,j.length,y);if(b!=Eb)i=Db}}else if(b!=Eb){w(b);b=Eb}if(q>0&&h){if(c==Eb){c=db(TID_HEADER,q,yb);if(c!=Eb)i=Db}}else if(c!=Eb){w(c);c=Eb}if(c!=Eb&&b!=Eb){if(e==Eb){e=db(TID_CORNER,q,y);i=Db}}else if(e!=Eb){w(e);e=Eb}return i}
        function wb(){if(c!=Eb){s(c,_offsetWidth(d));U(c)}if(b!=Eb){var g=_colsWidth(_cells(d.rows[0]),y),f=_colsWidth(_cells(b.rows[0]),y),a=f-g;a!=0&&s(b,_offsetWidth(b)-a);U(b);A(b,_offsetHeight(d))}if(e!=Eb){s(e,_offsetWidth(b));U(e);A(e,_offsetHeight(c))}}
        function zb(){var j=1,d=c==Eb?Eb:c.parentNode,f=b==Eb?Eb:b.parentNode,g=e==Eb?Eb:e.parentNode;d!=Eb&&D(d);f!=Eb&&D(f);g!=Eb&&D(g);if(d!=Eb){F(d,a.clientWidth);E(d,_offsetHeight(c));var i=_rect(c).bottom-_rect(d).bottom;i>0&&E(d,_offsetHeight(c)+i);d.clientHeight>=a.clientHeight&&E(d,a.clientHeight-j)}if(f!=Eb){E(f,a.clientHeight);F(f,_offsetWidth(b));var h=_rect(b).right-_rect(f).right;h>0&&F(f,_offsetWidth(b)+h);f.clientWidth>=a.clientWidth&&F(f,a.clientWidth-j)}if(g!=Eb){E(g,d.clientHeight);F(g,f.clientWidth)}}
        function rb(){var b=a.cloneNode(Cb),c=d.cloneNode(Cb);b.style.position=Mb;b.style.left=Nb;b.style.top=Nb;b.style.minWidth=g;b.style.minHeight=g;a.parentNode.appendChild(b);var f=_rect(a),e=_rect(b);pb=f.top-e.top;ob=f.left-e.left;c.style.width="50px";c.style.height="50px";var h=document.createElement(i),k=document.createElement("TR"),j=document.createElement(Ob);j.appendChild(document.createTextNode("x"));k.appendChild(j);h.appendChild(k);c.appendChild(h);var m=b.offsetWidth,l=b.offsetHeight;b.appendChild(c);p=b.offsetWidth!=m;x=b.offsetHeight!=l;if(!p)v=Fb;if(!x)z=Fb;if(v>0)p=Cb;if(z>0)x=Cb;W=_offsetWidth(b)-_offsetWidth(c);V=_offsetHeight(b)-_offsetHeight(c);b.parentNode.removeChild(b)}
        function jb(){if(q==0&&y==0)return;var a=d.cloneNode(Cb);a.style.position=Mb;a.style.left=Nb;a.style.top=Nb;a.style.width=Jb;a.style.height=Jb;a.width=Ib;a.height=Ib;var f,h=_getElementByTagName(d,Hb);if(h==Eb)h=_getElementByTagName(d,i);if(h!=Eb)f=h.cloneNode(Cb);else f=document.createElement(i);a.appendChild(f);d.parentNode.appendChild(a);for(var p=q>0?q:1,n=d.rows,o=0,c=0;c<p;c++){var k=n[c],j=k.cloneNode(Cb);j.style.height=_trHeight(k)+PX;for(var g=_cells(k),e=0;e<g.length;e++){var m=g[e],b=m.cloneNode(Cb);b.width=Ib;if(m.colSpan==1)b.style.width=o+PX;else b.style.width=Jb;b.appendChild(document.createTextNode(" "));j.appendChild(b)}f.appendChild(j);if(_isIE&&_IEver<=7&&!_isBackCompat){R=_trHeight(j)-_trHeight(k);R+=2}}for(var c=0;c<p;c++)for(var g=_cells(n[c]),r=_cells(f.rows[c]),e=0;e<g.length;e++){var m=g[e],b=r[e];if(b.style.width==Jb)continue;var l=c+"."+m.cellIndex;lb[l]=_offsetWidth(b)-b.clientWidth;B[l]=b.clientWidth-o;X=Math.max(B[l],X)}a.parentNode.removeChild(a)}
        function db(e,s,t){var k=" fixed_header_display_none_at_print",c=d.cloneNode(Cb),o=_getElementByTagName(d,"CAPTION"),p=_getElementByTagName(d,Hb),r=_getElementByTagName(d,i),j=Eb,m=Eb,l=Eb;if(o!=Eb){j=o.cloneNode(Db);j.style.backgroundColor=J;j.style.overflow=Kb;if(e!=TID_HEADER){j.innerHTML="&nbsp;";j.style.height=_offsetHeight(o)+PX;j.style.backgroundColor=Pb}c.appendChild(j)}var q=0;if(p!=Eb){m=p.cloneNode(Cb);c.appendChild(m);q=p.rows.length}if(r!=Eb&&q<s){l=r.cloneNode(Cb);c.appendChild(l)}if(Ab(l,m,e,s,t,q)==Cb)return Eb;_linkElement(c,d,e,C,Cb);j!=Eb&&_linkElement(j,o,e,C,Db);m!=Eb&&_linkElement(m,p,e,C,Cb);l!=Eb&&_linkElement(l,r,e,C,Cb);if(e!=TID_HEADER){c.style.marginRight=Nb;c.style.borderRightWidth=Nb;c.style.paddingRight=Nb}if(e!=TID_NUMBER){c.style.marginBottom=Nb;c.style.borderBottomWidth=Nb;c.style.paddingBottom=Nb}c.style.minWidth=g;c.style.minHeight=g;if(f){var b=a.cloneNode(Cb);b.$FXH_PADDING_WIDTH=undefined;b.$FXH_PADDING_HEIGHT=undefined;_linkElement(b,a,e,C,Cb);b.className+=k;b.style.overflowX=Kb;b.style.overflowY=Kb;_removeEventListener(b,Gb,S);e!=TID_CORNER&&_addEventListener(b,Gb,function(){tb(b,e)});if(e==TID_HEADER)b.style.borderRightWidth=Nb;else{b.style.marginRight=Nb;b.style.borderRightWidth=Nb;b.style.paddingRight=Nb}if(e==TID_NUMBER)b.style.borderBottomWidth=Nb;else{b.style.marginBottom=Nb;b.style.borderBottomWidth=Nb;b.style.paddingBottom=Nb}b.style.width="30px";b.style.height="30px";b.style.minWidth=g;b.style.minHeight=g;b.style.position=Mb;b.style.top=pb+PX;b.style.left=ob+PX;b.style.backgroundColor=J;b.appendChild(c);a.parentNode.appendChild(b)}else{c.className+=k;switch(_positionMode){case POS_FIXED:c.style.position=h;break;case POS_ABSOLUTE:c.style.position=Mb;break;default:c.style.position=h}c.style.marginTop=Nb;c.style.marginLeft=Nb;c.style.top=Nb;c.style.left=Nb;c.style.backgroundColor=J;d.parentNode.appendChild(c)}_isOpera&&n(f?b:c,Cb);return c}
        function Ab(o,p,g,v,r,w){for(var f=new Array(r),h=0;h<f.length;h++)f[h]=0;for(var t=d.rows,c=0;c<v;c++){var k=t[c],b=k.cloneNode(Cb);_linkElement(b,k,g,C,Cb);b.style.height=_trHeight(k)-R+PX;if(c==q-1&&g!=TID_NUMBER){if(G!=Eb)b.style.borderBottomColor=G;if(H!=Eb)b.style.borderBottomStyle=H;if(I!=Eb)b.style.borderBottomWidth=I}if(g!=TID_HEADER)b.style.borderRightWidth=Nb;if(c<w)p.appendChild(b);else o.appendChild(b);for(var u=_cells(k),l=0,e=0;e<r;){if(c<f[e]){e++;continue}if(l>=u.length)break;var a=u[l];l++;if(c+a.rowSpan>v)return Cb;f[e]=c+a.rowSpan;if(a.colSpan>=2){for(var h=1;h<a.colSpan;h++)f[e+h]=f[e];if(e+a.colSpan>r)return Cb}_radioCtl(a,"backup");var j=a.cloneNode(Db);_radioCtl(a,"restore");_linkElement(j,a,g,C,Db);b.appendChild(j);try{var n=c+"."+a.cellIndex;if(B[n]!=undefined){var A=B[n]+lb[n];j.style.width=_offsetWidth(a)-A+PX}else if(_isIE&&_IEver<=8&&a.colSpan>1)j.style.width=a.clientWidth-X+PX}catch(D){}var i=j.style;if(c+a.rowSpan==q&&g!=TID_NUMBER){if(G!=Eb)i.borderBottomColor=G;if(H!=Eb)i.borderBottomStyle=H;if(I!=Eb)i.borderBottomWidth=I}if(e+a.colSpan==y&&g!=TID_HEADER){if(G!=Eb)i.borderRightColor=G;if(H!=Eb)i.borderRightStyle=H;if(I!=Eb)i.borderRightWidth=I}e+=a.colSpan}if(_isIE&&_IEver<=9&&l==0){b.style.height=Nb;var x=_rect(k).bottom,s=b.parentNode.rows,m=c-1;while(s[m].style.height==Nb)m--;var z=x-_rect(t[m]).top;s[m].style.height=z-R+PX}}p!=Eb&&_radioCtl(p,Qb);o!=Eb&&_radioCtl(o,Qb);return Db}
        function D(b){var f=_rect(a),e=_rect(b),d=e.top-f.top,c=e.left-f.left;if(_isIE){if(d==Fb&&b.$TOP_DIFF==1)d=0;else b.$TOP_DIFF=d;if(c==Fb&&b.$LEFT_DIFF==1)c=0;else b.$LEFT_DIFF=c}if(d!=0)b.style.top=_pixel(b.style.top)-d+PX;if(c!=0)b.style.left=_pixel(b.style.left)-c+PX}
        function w(a){if(f)a=a.parentNode;_unlinkElement(a);a.parentNode.removeChild(a)}
        o.onBodyScroll=function(){if(f)return;if(_positionMode==POS_ABSOLUTE){if(!_isMobile){if(_getBodyScrollTop()!=t){n(c,Cb);n(e,Cb)}if(_getBodyScrollLeft()!=r){n(b,Cb);n(e,Cb)}}M!=Eb&&clearTimeout(M);M=setTimeout(bb,200)}else bb()};
        function bb(j){M=Eb;var i=_getBodyScrollTop()!=t,g=_getBodyScrollLeft()!=r;t=_getBodyScrollTop();r=_getBodyScrollLeft();if(i&&g)j=Db;var f=_rect(d),m=c!=Eb&&f.top<0&&f.bottom>=c.offsetHeight,o=b!=Eb&&f.left<0&&f.right>=b.offsetWidth;c!=Eb&&n(c,m);b!=Eb&&n(b,o);e!=Eb&&n(e,m&&o);if(_positionMode==POS_MIX&&c!=Eb){var a=c.style;if(j||i&&a.position==Mb){a.position=h;a.left=f.left+PX;a.top=Nb;O(Cb)}else if(!i&&g&&a.position==h){a.position=Mb;a.left=r+f.left+PX;a.top=t+PX;ib()}}if(_positionMode==POS_MIX&&b!=Eb){var a=b.style;if(j||g&&a.position==Mb){a.position=h;a.left=Nb;a.top=f.top+PX;P(Cb)}else if(!g&&i&&a.position==h){a.position=Mb;a.top=t+f.top+PX;a.left=r+PX;hb()}}if(_positionMode==POS_FIXED){if(c!=Eb&&g)c.style.left=f.left+PX;if(b!=Eb&&i)b.style.top=f.top+PX}if(_positionMode==POS_ABSOLUTE&&j){if(c!=Eb)c.style.left=r+f.left+PX;if(b!=Eb)b.style.top=t+f.top+PX}if(_positionMode==POS_ABSOLUTE&&(i||g)){var l,k,p=_isMobile?1:4;if(c!=Eb&&i){c.style.top=t-_offsetHeight(c)+PX;if(e!=Eb)e.style.top=c.style.top;l=(t-_pixel(c.style.top))/p}if(b!=Eb&&g){b.style.left=r-_offsetWidth(b)+PX;if(e!=Eb)e.style.left=b.style.left;k=(r-_pixel(b.style.left))/p}K!=Eb&&clearTimeout(K);gb(i,g,l,k)}c!=Eb&&g&&O(Cb);b!=Eb&&i&&P(Cb)}
        function gb(k,i,j,h){K=Eb;var g=_getBodyScrollTop(),f=_getBodyScrollLeft(),d=g,a=f;if(c!=Eb&&k){d=_pixel(c.style.top)+j;if(j>0)d=Math.min(d,g);else d=Math.max(d,g);c.style.top=d+PX;if(e!=Eb)e.style.top=c.style.top}if(b!=Eb&&i){a=_pixel(b.style.left)+h;if(h>0)a=Math.min(a,f);else a=Math.max(a,f);b.style.left=a+PX;if(e!=Eb)e.style.left=b.style.left}if(g==d&&f==a){if(c!=Eb&&k){ib();if(e!=Eb)e.style.top=c.style.top}if(b!=Eb&&i){hb();if(e!=Eb)e.style.left=b.style.left}return}var l=function(){gb(k,i,j,h)};
            K=setTimeout(l,20)}
        function S(){var d=c==Eb?Eb:c.parentNode,f=b==Eb?Eb:b.parentNode,g=e==Eb?Eb:e.parentNode;n(d,a.scrollTop>0);n(f,a.scrollLeft>0);n(g,a.scrollTop>0&&a.scrollLeft>0);d!=Eb&&D(d);f!=Eb&&D(f);g!=Eb&&D(g);var h=a.scrollLeft!=ab,i=a.scrollTop!=cb;ab=a.scrollLeft;cb=a.scrollTop;if(d!=Eb&&h){d.$FXH_SCROLL_LEFT=a.scrollLeft;d.scrollLeft=a.scrollLeft;d.scrollLeft>0&&O(Cb)}if(f!=Eb&&i){f.$FXH_SCROLL_TOP=a.scrollTop;f.scrollTop=a.scrollTop;f.scrollTop>0&&P(Cb)}}
        function tb(b,c){if(c==TID_HEADER){if(Math.abs(b.scrollLeft-b.$FXH_SCROLL_LEFT)<5)return}else if(Math.abs(b.scrollTop-b.$FXH_SCROLL_TOP)<5)return;if(c==TID_HEADER)a.scrollLeft=b.scrollLeft;else a.scrollTop=b.scrollTop}
        function ib(){if(c==Eb)return;var a=_rect(c);if(a.top<=0)return;c.style.top=_pixel(c.style.top)-a.top+PX}
        function hb(){if(b==Eb)return;var a=_rect(b);if(a.left<=0)return;b.style.left=_pixel(b.style.left)-a.left+PX}
        function O(p){if(c==Eb)return;if(!p){L!=Eb&&clearTimeout(L);L=setTimeout(function(){O(Db)},200);return}L=Eb;var g,j;if(f){g=_rect(a).left;j=g+a.clientWidth}else{g=0;j=_body.clientWidth}if(b!=Eb&&b.style.visibility==u)g+=_offsetWidth(b);for(var m=_cells(d.rows[0]),n=_cells(c.rows[0]),e=0,l=0,h=0;h<m.length;h++){var k=_rect(m[h]).left;if(k<g)continue;if(k>j)break;var o=_rect(n[h]).left;e+=o-k;l++}if(l==0)return;if(e==0)return;e=e/l;e=Math.round(e);if(e==0)return;if(f){var i=c.parentNode;i.$FXH_SCROLL_LEFT=i.scrollLeft+e;i.scrollLeft+=e}else{var q=_pixel(c.style.left)-e;c.style.left=q+PX}}
        function P(o){if(b==Eb)return;if(_isOpera)return;if(!o){N!=Eb&&clearTimeout(N);N=setTimeout(function(){P(Db)},200);return}N=Eb;var g,j;if(f){g=_rect(a).top;j=g+a.clientHeight}else{g=0;j=_body.clientHeight}if(c!=Eb&&c.style.visibility==u)g+=_offsetHeight(c);for(var n=d.rows,m=b.rows,e=0,l=0,h=0;h<n.length;h++){var k=_rect(n[h]).top;if(k<g)continue;if(k>j)break;if(_cells(m[h]).length==0)continue;var p=_rect(m[h]).top;e+=p-k;l++}if(l==0)return;if(e==0)return;e=e/l;e=Math.round(e);if(e==0)return;if(f){var i=b.parentNode;i.$FXH_SCROLL_TOP=i.scrollTop+e;i.scrollTop+=e}else{var q=_pixel(b.style.top)-e;b.style.top=q+PX}}
        function n(a,b){if(a==Eb)return;var c=b?u:Kb;if(a.style.visibility==c)return;a.style.visibility=c;if(_isIE)a.style.zIndex=b?qb+1:qb-1;if(_isOpera)a.style.opacity=b?T:0;if(b&&T<1){a.style.opacity=T;a.style.filter="alpha(opacity="+T*100+")"}}
        function ub(b){if(!_isIE&&!_isIE11&&!_isFirefox&&!_isOpera)return;if(b){k=sb();a.appendChild(k);s(k,_offsetWidth(d));A(k,_offsetHeight(d));d.style.display=Lb}else{d.style.display=xb;a.removeChild(k);k=Eb}}
        function sb(){var a=d.cloneNode(Cb),b=document.createElement(i),e=document.createElement("TR"),c=document.createElement(Ob);c.appendChild(document.createTextNode("dummy"));e.appendChild(c);b.appendChild(e);a.appendChild(b);return a}
        function F(a,b){nb(a,m,b)}
        function s(a,b){nb(a,"OFFSET",b)}
        function E(a,b){mb(a,m,b)}
        function A(a,b){mb(a,"OFFSET",b)}
        function nb(a,g,f){var b=f;if(a.$FXH_PADDING_WIDTH!=undefined)b-=a.$FXH_PADDING_WIDTH;for(var d,c,e=0;e<2;e++){if(b<MIN_SIZE)b=MIN_SIZE;a.style.width=b+PX;d=g==m?a.clientWidth:_offsetWidth(a);c=d-f;if(a.$FXH_PADDING_WIDTH==undefined)a.$FXH_PADDING_WIDTH=c;if(c==0||b==MIN_SIZE)break;b-=c}}
        function mb(a,g,e){var b=e;if(a.$FXH_PADDING_HEIGHT!=undefined)b-=a.$FXH_PADDING_HEIGHT;for(var d,c,f=0;f<2;f++){if(b<MIN_SIZE)b=MIN_SIZE;a.style.height=b+PX;d=g==m?a.clientHeight:_offsetHeight(a);c=d-e;if(a.$FXH_PADDING_HEIGHT==undefined)a.$FXH_PADDING_HEIGHT=c;if(c==0||b==MIN_SIZE)break;b-=c}}
        function U(p){var g=d.rows,c=p.rows,e=c.length,k=_rowsHeight(g,e)+HEIGHT_MARGIN;if(_rowsHeight(c,e)<k)return;for(var a=0;a<e;a++){var q=_trHeight(c[a])-_trHeight(g[a]);if(q<HEIGHT_MARGIN)continue;for(var o=_cells(g[a]),j=_cells(c[a]),f=0;f<j.length;f++){var l=o[f],i=j[f],b=0,h=a+"."+l.cellIndex;if(B[h]!=undefined){if(B[h]<=0)continue;b=B[h]-2;if(b<0)b=0}var n=Math.ceil(b/2),m=Math.floor(b/2);i.style.paddingLeft=n+PX;i.style.paddingRight=m+PX;i.style.width=l.clientWidth-b+PX;if(_rowsHeight(c,e)<k)return}}}}
    function _FixedElementList(){var b=this,a=[];
        b.add=function(b){a.push(b)};
        b.remove=function(c){for(var b=0;b<a.length;b++)if(a[b]==c){a.splice(b,1);return}};
        b.get=function(d){for(var b=0;b<a.length;b++){var c=a[b];if(c.$SOURCE_ELEMENT==d)return c}return Eb};
        b.getAll=function(e){for(var b=Eb,c=0;c<a.length;c++){var d=a[c];if(d.$SOURCE_ELEMENT==e){if(b==Eb)b=[];b.push(d)}}return b}}
    function _linkElement(b,a,i,g,f){a.id&&!g&&b.removeAttribute("id");if(a.name)if(a.tagName==j&&a.type==k)b.name=RADIO_PREFIX+i+"_"+a.name;else b.removeAttribute("name");b.$SOURCE_ELEMENT=a;if(_fixedList!=Eb)_fixedList.add(b);else if(!a.$FXH_FIXED_ELEMENT)a.$FXH_FIXED_ELEMENT=b;else{var h=a.$FXH_FIXED_ELEMENT;if(!h.$IS_ARRAY){var d=[];d.$IS_ARRAY=Db;a.$FXH_FIXED_ELEMENT=d;d.push(h)}a.$FXH_FIXED_ELEMENT.push(b)}_setEventHandler(b,a);if(f)for(var c=0;c<b.childNodes.length;c++){var e=b.childNodes[c];if(!e)continue;if(!e.tagName)continue;_linkElement(e,a.childNodes[c],i,g,f)}}
    function _unlinkElement(c){if(_fixedList!=Eb){_fixedList.remove(c);var a=c.$SOURCE_ELEMENT;if(a&&a.$FXH_ON_CHANGE_FUNC&&_fixedList.get(a)==Eb){_removeEventListener(a,g,a.$FXH_ON_CHANGE_FUNC);a.$FXH_ON_CHANGE_FUNC=undefined}}else{var a=c.$SOURCE_ELEMENT;if(a&&a.$FXH_FIXED_ELEMENT){var d=a.$FXH_FIXED_ELEMENT;if(!d.$IS_ARRAY||d.length==1){a.$FXH_FIXED_ELEMENT=undefined;if(a.$FXH_ON_CHANGE_FUNC){_removeEventListener(a,g,a.$FXH_ON_CHANGE_FUNC);a.$FXH_ON_CHANGE_FUNC=undefined}}else{for(var f=[],b=0;b<d.length;b++)d[b]!=c&&f.push(d[b]);a.$FXH_FIXED_ELEMENT=f}}}for(var b=0;b<c.childNodes.length;b++){var e=c.childNodes[b];if(!e)continue;if(!e.tagName)continue;_unlinkElement(e)}}
    function _setEventHandler(b,a){if(a.onclick)b.onclick=function(){return a.onclick()};
        if(a.ondblclick)b.ondblclick=function(){return a.ondblclick()};
        if(a.onkeydown)b.onkeydown=function(){return a.onkeydown()};
        if(a.onkeypress)b.onkeypress=function(){return a.onkeypress()};
        if(a.onkeyup)b.onkeyup=function(){return a.onkeyup()};
        if(a.onmousedown)b.onmousedown=function(){return a.onmousedown()};
        if(a.onmouseup)b.onmouseup=function(){return a.onmouseup()};
        if(a.onmouseover)b.onmouseover=function(){return a.onmouseover()};
        if(a.onmouseout)b.onmouseout=function(){return a.onmouseout()};
        if(a.onmousemove)b.onmousemove=function(){return a.onmousemove()};
        if(a.tagName==j||a.tagName=="SELECT"||a.tagName=="TEXTAREA"){switch(a.type){case e:case f:case h:_copyValue(a,b)}switch(a.type){case h:case k:case e:case f:case "text":case i:case l:b.onclick=function(){_copyValue(b,a);_copyValues(a,b);if(a.onclick)return a.onclick();return Db};
            b.onchange=function(){_copyValue(b,a);_copyValues(a,b);if(a.onchange)return a.onchange();return Db};
            if(a.$FXH_ON_CHANGE_FUNC==undefined){a.$FXH_ON_CHANGE_FUNC=function(){_copyValues(a)};
                _addEventListener(a,g,a.$FXH_ON_CHANGE_FUNC)}}}else if(a.tagName=="FORM")b.onsubmit=function(){return Cb}}
    function _copyValues(d,c){if(c==undefined)c=Eb;var a;if(_fixedList!=Eb){a=_fixedList.getAll(d);if(!a)return;for(var b=0;b<a.length;b++){if(a[b]==c)continue;_copyValue(d,a[b])}return}a=d.$FXH_FIXED_ELEMENT;if(!a)return;if(!a.$IS_ARRAY)a!=c&&_copyValue(d,a);else for(var b=0;b<a.length;b++){if(a[b]==c)continue;_copyValue(d,a[b])}}
    function _copyValue(a,b){switch(a.type){case h:case k:b.checked=a.checked;break;case e:case f:for(var c=0;c<a.length;c++)b.options[c].selected=a.options[c].selected;b.selectedIndex=a.selectedIndex;break;case "text":case i:case l:b.value=a.value;break;default:try{b.value=a.value}catch(d){}}}
    function _copyStyle(src,dst,styleName){for(var buf=styleName.split(","),i=0;i<buf.length;i++){var name=_trim(buf[i]);try{eval("dst.style."+name+" = src.style."+name)}catch(e){}}}
    function _setStyle(element,styleName,value){try{eval("element.style."+styleName+" = value");return Db}catch(e){return Cb}}
    function _radioCtl(d,e){for(var c=d.getElementsByTagName(j),b=0;b<c.length;b++){var a=c[b];if(a.type!=k)continue;switch(e){case "backup":a.$FXH_CHECKED=a.checked;break;case "restore":a.checked=a.$FXH_CHECKED;break;case Qb:a.checked=a.$SOURCE_ELEMENT.checked}}}
    function _createCSS(c,b){var a=document.createElement("STYLE");a.setAttribute("type","text/css");a.setAttribute("media",c);if(a.styleSheet)a.styleSheet.cssText=b;else a.appendChild(document.createTextNode(b));_body.appendChild(a)}
    function _getBackgroundColor(d){var e=d.currentStyle||document.defaultView.getComputedStyle(d,Ib),a=e.backgroundColor;if(a==Pb)return Eb;if(a.match(/^rgba\(/)==Eb)return a;var g=a.replace(/^rgba\(/,Ib).replace(/\)/,Ib),c=g.split(","),b=Number(c[3]);if(b==1)return a;var f="rgb("+_color(Number(c[0]),b)+", "+_color(Number(c[1]),b)+", "+_color(Number(c[2]),b)+")";return f}
    function _color(a,b){var c=Math.round(a+(255-a)*(1-b));return Math.min(c,255)}
    function _addEventListener(a,b,c){if(a.addEventListener)a.addEventListener(b,c,Cb);else a.attachEvent&&a.attachEvent("on"+b,c)}
    function _removeEventListener(a,b,c){if(a.removeEventListener)a.removeEventListener(b,c,Cb);else a.detachEvent&&a.detachEvent("on"+b,c)}
    function _getBodyScrollTop(){if(_isBackCompat)return document.body.scrollTop;if(_isChrome||_isSafari)return document.body.scrollTop;return document.documentElement.scrollTop}
    function _getBodyScrollLeft(){if(_isBackCompat)return document.body.scrollLeft;if(_isChrome||_isSafari)return document.body.scrollLeft;return document.documentElement.scrollLeft}
    function _offsetWidth(b){var a=_rect(b);return a.right-a.left}
    function _offsetHeight(b){var a=_rect(b);return a.bottom-a.top}
    function _rowsHeight(a,b){return _rect(a[b-1]).bottom-_rect(a[0]).top}
    function _colsWidth(a,c){for(var d=0,b=0;b<a.length;b++){d+=a[b].colSpan;if(d==c){c=b+1;break}}return _rect(a[c-1]).right-_rect(a[0]).left}
    function _colsWidthList(c){for(var b=Ib,a=0;a<c.length;a++){if(a>0)b+=",";b+=c[a].offsetWidth}return b}
    function _rowsHeightList(c){for(var b=Ib,a=0;a<c.length;a++){if(a>0)b+=",";b+=c[a].offsetHeight}return b}
    function _trHeight(a){if(_isIE&&_IEver==8&&!_isBackCompat)return a.clientHeight;else return _offsetHeight(a)}
    function _cells(g){var a=g.getElementsByTagName(Ob),b=g.getElementsByTagName("TH");if(a.length==0&&b.length==0)return a;if(a.length>0&&b.length==0)return a;if(a.length==0&&b.length>0)return b;for(var e=a[0].parentNode.childNodes,f=[],d=0;d<e.length;d++){var c=e[d];(c.tagName==Ob||c.tagName=="TH")&&f.push(c)}return f}
    function _pixel(a){if(a.match(/px$/)!=Eb)a=a.substring(0,a.length-2);return Number(a)}
    function _percent(a){if(a.match(/%$/)!=Eb)a=a.substring(0,a.length-1);return Number(a)}
    function _trim(a){return a.replace(/^[ \u7e32\u0080]+/,Ib).replace(/[ \u7e32\u0080]+$/,Ib)}
    function _rect(a){return a.getBoundingClientRect()}
    function _getElementByTagName(b,c){var a=b.getElementsByTagName(c);if(a.length==0)return Eb;return a[0]}
    function _createObjectForFirefox(){var a=document.createElement("SPAN");a.style.display=Lb;a.style.position=Mb;a.style.top=Nb;a.style.left=Nb;document.body.appendChild(a);return a}
}
